name: Build

on:
  push:
    branches:
      - main


jobs:
  tests:
      name: Run Unit Tests
      runs-on: ubuntu-latest
      steps:
        # 1. Clonar el repositorio
        - uses: actions/checkout@v4
  
        # 2. Instalar dependencias necesarias
        - name: Install dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y cmake build-essential
  
        # 3. Configurar, compilar y ejecutar las pruebas
        - name: Configure, Build, and Test
          run: |
            mkdir build
            cd build
            cmake ..
            cmake --build .
            ctest --output-on-failure

        - name: Run test1
          run: |
            g++ tests/test1.cpp -o tests/test1
            chmod +x tests/test1
            ./tests/test1

        - name: Run test2
          run: |
            g++ tests/test2.cpp -o tests/test2
            chmod +x tests/test2
            ./tests/test2
